## Sample circle.yml file  https://circleci.com/docs/2.0/sample-config/

version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: ruby -v
  test:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: bundle install
      - run: export AWS_DEFAULT_REGION=ap-northeast-1
      - run: cd spec && bundle exec rake spec
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
