## Sample circle.yml file  https://circleci.com/docs/2.0/sample-config/

version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run: ruby -v
  test:
    docker:
      - image: circleci/ruby:2.4.2
      # circleci/ruby@sha256:91fa706ab0d1c49a1cf69b1803187e3663577477cb8e73542cdad1c8e2ecd771
      # see https://discuss.circleci.com/t/failed-to-invoke-bundler-on-circleci-2-0-with-circleci-ruby-2-4-2/18480/4
      # see https://github.com/circleci/circleci-images/issues/112
    steps:
      - checkout
      - run: bundle install
      - run: export AWS_DEFAULT_REGION=ap-northeast-1
      - run: cd spec && bundle exec rake spec
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
